imports:
  - php

filter:
  excluded_paths: [vendor/*, test/*]

build:
  image: default-bionic
  nodes:
    my-tests:
      environment:
        php:
          version: 8.3
      project_setup:
        before:
          - mkdir -p public/build
          - echo '{}' > public/build/entrypoints.json
      commands:
        - composer install --no-dev --no-scripts
        - composer dump-autoload
      tests:
        override:
          - phpunit --coverage-clover=docs/coverage.clover
    analysis:
      tests:
        override:
          - php-scrutinizer-run
