filter:
    excluded_paths: [vendor/*, tests/*]

build:
    image: default-jammy

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                node:
                    version: 18 # Node behövs för Webpack
            dependencies:
                before:
                    - yarn install    # Installera npm-paket (för webpack m.m.)
            tests:
                override:
                    - php -v
                    - composer install --no-interaction --prefer-dist
                    - yarn build      # Kör webpack för att generera entrypoints.json
                    - ./vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover=docs/coverage.clover

        analysis:
            environment:
                php:
                    version: 8.3.3
            tests:
                override:
                    - php-scrutinizer-run
