imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*]

tools:
    php_code_sniffer: true
    php_cpd: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_sim: true
    php_analyzer: true
    external_code_coverage: true

build:
    image: default-jammy

    cache:
        directories:
            - ~/.composer/cache/

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
            dependencies:
                before:
                    - composer install --no-progress --no-interaction
            tests:
                override:
                    - command: "php -v"
                    - command: "mkdir -p public/build && echo '{}' > public/build/entrypoints.json"
                    - command: "XDEBUG_MODE=coverage composer phpunit"
                      coverage:
                          file: "docs/coverage.clover"
                          format: "php-clover"

        analysis:
            environment:
                php:
                    version: 8.3.3
            tests:
                override:
                    - php-scrutinizer-run
