filter:
    excluded_paths: [vendor/*, test/*]

build:
    nodes:
        coverage:
            environment:
                php:
                    version: 8.3.3
            tests:
                override:
                    - command: "composer install"
                    - command: "vendor/bin/phpunit --coverage-clover=coverage.clover"
                      coverage:
                          file: "coverage.clover"
                          format: "php-clover"

        analysis:
            environment:
                php:
                    version: 8.3.3
            tests:
                override:
                    - php-scrutinizer-run

tools:
    external_code_coverage: true
    php_code_sniffer: true
    php_cpd: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
