imports:
  - php

filter:
  excluded_paths: [vendor/*, test/*]

build:
  image: default-bionic

dependencies:
  before:
    - composer self-update --2
    - composer install --ignore-platform-reqs --no-interaction

tests:
  override:
    - command: "composer phpunit"
      coverage:
        file: "docs/coverage.clover"
        format: "php-clover"

checks:
  php:
    code_rating: true
