imports:
  - php

filter:
  excluded_paths: [vendor/*, test/*]

build:
  image: default-bionic

environment:
  COMPOSER_NO_AUTO_SCRIPTS: '1'

build:
  nodes:
    my-tests:
      environment:
        php:
          version: 8.3
      project_setup:
        - mkdir -p public/build
        - mkdir -p public/build
        - echo '{}' > public/build/entrypoints.json

      commands:
        - composer install --no-dev --no-scripts
        - composer dump-autoload
      tests:
        override:
          - phpunit --coverage-clover=docs/coverage.clover
    analysis:
      tests:
        override:
          - php-scrutinizer-run
