filter:
    excluded_paths: [vendor/*, test/*]

build:
    image: default-jammy

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
            tests:
                override:
                    - command: "php -v"
                    - command: "composer install"
                    - command: "composer phpunit"
                      coverage:
                          file: "docs/coverage.clover"
                          format: "php-clover"

        analysis:
            environment:
                php:
                    version: 8.3.3
            tests:
                override:
                    - php-scrutinizer-run

        tools:
            external_code_coverage: true