imports:
    - php

filter:
    excluded_paths: [vendor/*, tests/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
            dependencies:
                before:
                    - curl -sS https://getcomposer.org/installer | php -- --2
                    - php composer.phar --version
                    - php composer.phar install
            tests:
                override:
                    - command: "php composer.phar phpunit"
                      coverage:
                          file: "docs/coverage.clover"
                          format: "php-clover"

        analysis:
            tests:
                override:
                    - php-scrutinizer-run
