imports:
  - php

filter:
  excluded_paths: [vendor/*, test/*]

build:
  image: default-bionic

  nodes:
    my-tests:
      environment:
        php:
          version: 8.3.3
    analysis:
      tests:
        override:
          - php-scrutinizer-run

  dependencies:
    before:
      - composer self-update --2
      - composer install --ignore-platform-reqs --no-interaction

tests:
  override:
    - command: "composer phpunit"
      coverage:
        file: "docs/coverage.clover"
        format: "php-clover"
