filter:
    excluded_paths: [vendor/*, tests/*]

build:
    image: default-jammy

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                node:
                    version: 18
            dependencies:
                before:
                    - npm install
                    - npm run build
                    - php bin/console doctrine:database:create --env=test
                    - php bin/console doctrine:schema:create --env=test
            tests:
                override:
                    - php -v
                    - composer install --no-interaction --prefer-dist
                    - ./vendor/bin/phpunit --coverage-clover=docs/coverage.clover

        analysis:
            environment:
                php:
                    version: 8.3.3
            tests:
                override:
                    - php-scrutinizer-run
