imports:
    - php

filter:
    excluded_paths: [vendor/*, tests/*]

build:
    image: default-bionic

    environment:
        php:
            version: 8.3

    dependencies:
        before:
            - composer self-update --2
            - composer install --ignore-platform-reqs --no-interaction

    tests:
        override:
            - command: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover=coverage.xml
              coverage:
                  file: coverage.xml
                  format: php-clover

tools:
    external_code_coverage: true
